export const getUsers = () => {
  return [
    {
      userName: "jdoe001",
      firstName: "John",
      lastName: "Doe",
      email: "johndoe001@example.com",
      status: "active",
    },
    {
      userName: "asmith002",
      firstName: "Alice",
      lastName: "Smith",
      email: "alicesmith002@example.com",
      status: "inactive",
    },
    {
      userName: "bjohnson003",
      firstName: "Bob",
      lastName: "Johnson",
      email: "bobjohnson003@example.com",
      status: "active",
    },
    {
      userName: "cmiller004",
      firstName: "Charlie",
      lastName: "Miller",
      email: "charliemiller004@example.com",
      status: "pending",
    },
    {
      userName: "drichardson005",
      firstName: "Diana",
      lastName: "Richardson",
      email: "dianarichardson005@example.com",
      status: "active",
    },
    {
      userName: "ethompson006",
      firstName: "Ethan",
      lastName: "Thompson",
      email: "ethanthompson006@example.com",
      status: "inactive",
    },
    {
      userName: "fgarcia007",
      firstName: "Fiona",
      lastName: "Garcia",
      email: "fionagarcia007@example.com",
      status: "active",
    },
    {
      userName: "ghernandez008",
      firstName: "George",
      lastName: "Hernandez",
      email: "georgehernandez008@example.com",
      status: "pending",
    },
    {
      userName: "hkhan009",
      firstName: "Hanna",
      lastName: "Khan",
      email: "hannakhan009@example.com",
      status: "active",
    },
    {
      userName: "iwilson010",
      firstName: "Ian",
      lastName: "Wilson",
      email: "ianwilson010@example.com",
      status: "inactive",
    },
    {
      userName: "jmoore011",
      firstName: "Jack",
      lastName: "Moore",
      email: "jackmoore011@example.com",
      status: "active",
    },
    {
      userName: "lwhite012",
      firstName: "Linda",
      lastName: "White",
      email: "lindawhite012@example.com",
      status: "inactive",
    },
    {
      userName: "mmartin013",
      firstName: "Mark",
      lastName: "Martin",
      email: "markmartin013@example.com",
      status: "active",
    },
    {
      userName: "nclark014",
      firstName: "Nancy",
      lastName: "Clark",
      email: "nancyclark014@example.com",
      status: "pending",
    },
    {
      userName: "opeterson015",
      firstName: "Olivia",
      lastName: "Peterson",
      email: "oliviapeterson015@example.com",
      status: "inactive",
    },
    {
      userName: "pqasim016",
      firstName: "Paul",
      lastName: "Qasim",
      email: "paulqasim016@example.com",
      status: "active",
    },
    {
      userName: "rlopez017",
      firstName: "Rachel",
      lastName: "Lopez",
      email: "rachellopez017@example.com",
      status: "inactive",
    },
    {
      userName: "skumar018",
      firstName: "Sanjay",
      lastName: "Kumar",
      email: "sanjaykumar018@example.com",
      status: "active",
    },
    {
      userName: "tgupta019",
      firstName: "Tanya",
      lastName: "Gupta",
      email: "tanyagupta019@example.com",
      status: "pending",
    },
    {
      userName: "uvarma020",
      firstName: "Usha",
      lastName: "Varma",
      email: "ushavarma020@example.com",
      status: "inactive",
    },
    {
      userName: "vsharma021",
      firstName: "Vikram",
      lastName: "Sharma",
      email: "vikramsharma021@example.com",
      status: "active",
    },
    {
      userName: "wjackson022",
      firstName: "William",
      lastName: "Jackson",
      email: "williamjackson022@example.com",
      status: "inactive",
    },
    {
      userName: "xnguyen023",
      firstName: "Xia",
      lastName: "Nguyen",
      email: "xiannguyen023@example.com",
      status: "pending",
    },
    {
      userName: "yadams024",
      firstName: "Yara",
      lastName: "Adams",
      email: "yaraadams024@example.com",
      status: "active",
    },
    {
      userName: "zbailey025",
      firstName: "Zoe",
      lastName: "Bailey",
      email: "zoebailey025@example.com",
      status: "inactive",
    },
    {
      userName: "amiller026",
      firstName: "Amir",
      lastName: "Miller",
      email: "amirmiller026@example.com",
      status: "active",
    },
    {
      userName: "bthomas027",
      firstName: "Brian",
      lastName: "Thomas",
      email: "brianthomas027@example.com",
      status: "pending",
    },
    {
      userName: "cgreen028",
      firstName: "Catherine",
      lastName: "Green",
      email: "catherinegreen028@example.com",
      status: "active",
    },
    {
      userName: "djohnson029",
      firstName: "Derek",
      lastName: "Johnson",
      email: "derekjohnson029@example.com",
      status: "inactive",
    },
    {
      userName: "ealexander030",
      firstName: "Eva",
      lastName: "Alexander",
      email: "evaalexander030@example.com",
      status: "pending",
    },
  ];
};
