import { defineStore } from "pinia";

export const useFakeUsersStore = defineStore("fakeUsers", {
  id: "fakeUsers",
  state: () => ({
    users: [
      {
        id: 1,
        userName: "jdoe001",
        firstName: "John",
        lastName: "Doe",
        email: "johndoe001@example.com",
        status: "active",
      },
      {
        id: 2,
        userName: "asmith002",
        firstName: "Alice",
        lastName: "Smith",
        email: "alicesmith002@example.com",
        status: "inactive",
      },
      {
        id: 3,
        userName: "bjohnson003",
        firstName: "Bob",
        lastName: "Johnson",
        email: "bobjohnson003@example.com",
        status: "active",
      },
      {
        id: 4,
        userName: "cmiller004",
        firstName: "Charlie",
        lastName: "Miller",
        email: "charliemiller004@example.com",
        status: "deleted",
      },
      {
        id: 5,
        userName: "drichardson005",
        firstName: "Diana",
        lastName: "Richardson",
        email: "dianarichardson005@example.com",
        status: "active",
      },
      {
        id: 6,
        userName: "ethompson006",
        firstName: "Ethan",
        lastName: "Thompson",
        email: "ethanthompson006@example.com",
        status: "inactive",
      },
      {
        id: 7,
        userName: "fgarcia007",
        firstName: "Fiona",
        lastName: "Garcia",
        email: "fionagarcia007@example.com",
        status: "active",
      },
      {
        id: 8,
        userName: "ghernandez008",
        firstName: "George",
        lastName: "Hernandez",
        email: "georgehernandez008@example.com",
        status: "deleted",
      },
      {
        id: 9,
        userName: "hkhan009",
        firstName: "Hanna",
        lastName: "Khan",
        email: "hannakhan009@example.com",
        status: "active",
      },
      {
        id: 10,
        userName: "iwilson010",
        firstName: "Ian",
        lastName: "Wilson",
        email: "ianwilson010@example.com",
        status: "inactive",
      },
      {
        id: 11,
        userName: "jmoore011",
        firstName: "Jack",
        lastName: "Moore",
        email: "jackmoore011@example.com",
        status: "active",
      },
      {
        id: 12,
        userName: "lwhite012",
        firstName: "Linda",
        lastName: "White",
        email: "lindawhite012@example.com",
        status: "inactive",
      },
      {
        id: 13,
        userName: "mmartin013",
        firstName: "Mark",
        lastName: "Martin",
        email: "markmartin013@example.com",
        status: "active",
      },
      {
        id: 14,
        userName: "nclark014",
        firstName: "Nancy",
        lastName: "Clark",
        email: "nancyclark014@example.com",
        status: "deleted",
      },
      {
        id: 15,
        userName: "opeterson015",
        firstName: "Olivia",
        lastName: "Peterson",
        email: "oliviapeterson015@example.com",
        status: "inactive",
      },
      {
        id: 16,
        userName: "pqasim016",
        firstName: "Paul",
        lastName: "Qasim",
        email: "paulqasim016@example.com",
        status: "active",
      },
      {
        id: 17,
        userName: "rlopez017",
        firstName: "Rachel",
        lastName: "Lopez",
        email: "rachellopez017@example.com",
        status: "inactive",
      },
      {
        id: 18,
        userName: "skumar018",
        firstName: "Sanjay",
        lastName: "Kumar",
        email: "sanjaykumar018@example.com",
        status: "active",
      },
      {
        id: 19,
        userName: "tgupta019",
        firstName: "Tanya",
        lastName: "Gupta",
        email: "tanyagupta019@example.com",
        status: "deleted",
      },
      {
        id: 20,
        userName: "uvarma020",
        firstName: "Usha",
        lastName: "Varma",
        email: "ushavarma020@example.com",
        status: "inactive",
      },
      {
        id: 21,
        userName: "vsharma021",
        firstName: "Vikram",
        lastName: "Sharma",
        email: "vikramsharma021@example.com",
        status: "active",
      },
      {
        id: 22,
        userName: "wjackson022",
        firstName: "William",
        lastName: "Jackson",
        email: "williamjackson022@example.com",
        status: "inactive",
      },
      {
        id: 23,
        userName: "xnguyen023",
        firstName: "Xia",
        lastName: "Nguyen",
        email: "xiannguyen023@example.com",
        status: "deleted",
      },
      {
        id: 24,
        userName: "yadams024",
        firstName: "Yara",
        lastName: "Adams",
        email: "yaraadams024@example.com",
        status: "active",
      },
      {
        id: 25,
        userName: "zbailey025",
        firstName: "Zoe",
        lastName: "Bailey",
        email: "zoebailey025@example.com",
        status: "inactive",
      },
      {
        id: 26,
        userName: "amiller026",
        firstName: "Amir",
        lastName: "Miller",
        email: "amirmiller026@example.com",
        status: "active",
      },
      {
        id: 27,
        userName: "bthomas027",
        firstName: "Brian",
        lastName: "Thomas",
        email: "brianthomas027@example.com",
        status: "deleted",
      },
      {
        id: 28,
        userName: "cgreen028",
        firstName: "Catherine",
        lastName: "Green",
        email: "catherinegreen028@example.com",
        status: "active",
      },
      {
        id: 29,
        userName: "djohnson029",
        firstName: "Derek",
        lastName: "Johnson",
        email: "derekjohnson029@example.com",
        status: "inactive",
      },
      {
        id: 30,
        userName: "ealexander030",
        firstName: "Eva",
        lastName: "Alexander",
        email: "evaalexander030@example.com",
        status: "deleted",
      },
    ],
  }),
  getters: {
    getUsers(state) {
      return state.users;
    },
  },
  actions: {},
});
